# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\QUI\fastboot.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(683, 508)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.device_label = QtWidgets.QLabel(self.centralwidget)
        self.device_label.setObjectName("device_label")
        self.horizontalLayout_3.addWidget(self.device_label)
        self.detect_btn = QtWidgets.QPushButton(self.centralwidget)
        self.detect_btn.setObjectName("detect_btn")
        self.horizontalLayout_3.addWidget(self.detect_btn)
        self.horizontalLayout_3.setStretch(0, 5)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.select_file_label = QtWidgets.QLabel(self.centralwidget)
        self.select_file_label.setObjectName("select_file_label")
        self.horizontalLayout.addWidget(self.select_file_label)
        self.filetype_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.filetype_comboBox.setObjectName("filetype_comboBox")
        self.horizontalLayout.addWidget(self.filetype_comboBox)
        self.Browse_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Browse_btn.setObjectName("Browse_btn")
        self.horizontalLayout.addWidget(self.Browse_btn)
        self.horizontalLayout.setStretch(0, 4)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.upgrade_progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.upgrade_progressBar.setProperty("value", 0)
        self.upgrade_progressBar.setTextVisible(False)
        self.upgrade_progressBar.setObjectName("upgrade_progressBar")
        self.horizontalLayout_2.addWidget(self.upgrade_progressBar)
        self.Upgrade_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Upgrade_btn.setEnabled(False)
        self.Upgrade_btn.setObjectName("Upgrade_btn")
        self.horizontalLayout_2.addWidget(self.Upgrade_btn)
        self.horizontalLayout_2.setStretch(0, 5)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.cmd_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.cmd_lineEdit.setObjectName("cmd_lineEdit")
        self.horizontalLayout_4.addWidget(self.cmd_lineEdit)
        self.cmd_send_btn = QtWidgets.QPushButton(self.centralwidget)
        self.cmd_send_btn.setEnabled(False)
        self.cmd_send_btn.setObjectName("cmd_send_btn")
        self.horizontalLayout_4.addWidget(self.cmd_send_btn)
        self.horizontalLayout_4.setStretch(0, 5)
        self.horizontalLayout_4.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.log_textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.log_textBrowser.setObjectName("log_textBrowser")
        self.verticalLayout.addWidget(self.log_textBrowser)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 683, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.device_label.setText(_translate("MainWindow", "Device Information"))
        self.detect_btn.setText(_translate("MainWindow", "Detect Device"))
        self.select_file_label.setText(_translate("MainWindow", "Select upgrade file"))
        self.Browse_btn.setText(_translate("MainWindow", "Browse"))
        self.Upgrade_btn.setText(_translate("MainWindow", "Upgrade"))
        self.cmd_send_btn.setText(_translate("MainWindow", "Send CMD"))
